"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Sparkles, Loader2, ChevronRight, X, BookOpen, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useVocabStore, type VocabWord } from "@/store/vocab-store"

// ─── Types ────────────────────────────────────────────────

type Step = "input" | "loading" | "preview" | "saved"

interface GeneratedWordData {
  word: string
  phonetic: string
  definition: string
  partOfSpeech: string
  examples: VocabWord["examples"]
  synonyms: string[]
}

// ─── Mock Gemini inference ────────────────────────────────
// TODO: Replace with real Gemini API call via /api/gemini route

async function mockGenerateWordData(word: string): Promise<GeneratedWordData> {
  await new Promise((r) => setTimeout(r, 1400))

  return {
    word,
    phonetic: "/ˌmɒk.fəˈnet.ɪk/",
    definition: `A detailed definition of "${word}" generated by AI, covering its primary meaning.`,
    partOfSpeech: "adjective",
    examples: [
      {
        sentence: `The ${word} nature of the situation was apparent to everyone.`,
        translation: `Tính chất "${word}" của tình huống rõ ràng với mọi người.`,
        context: "general",
      },
      {
        sentence: `She approached the problem with a ${word} mindset.`,
        translation: `Cô ấy tiếp cận vấn đề với tư duy "${word}".`,
        context: "personal",
      },
    ],
    synonyms: ["similar", "related", "alike"],
  }
}

// ─── Sub-components ───────────────────────────────────────

function StepIndicator({ step }: { step: Step }) {
  const steps: Step[] = ["input", "preview", "saved"]
  const idx = steps.indexOf(step === "loading" ? "preview" : step)

  return (
    <div className="flex items-center gap-1.5">
      {steps.slice(0, 2).map((s, i) => (
        <React.Fragment key={s}>
          <div
            className={[
              "size-1.5 rounded-full transition-all duration-300",
              i <= idx ? "bg-primary" : "bg-border",
            ].join(" ")}
          />
          {i < 1 && <div className={["h-px w-4 transition-all duration-300", i < idx ? "bg-primary" : "bg-border"].join(" ")} />}
        </React.Fragment>
      ))}
    </div>
  )
}

interface WordPreviewProps {
  data: GeneratedWordData
}

function WordPreview({ data }: WordPreviewProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-4"
    >
      {/* Word header */}
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-2xl font-bold text-foreground">{data.word}</h3>
          <p className="text-sm text-muted-foreground font-mono">{data.phonetic}</p>
        </div>
        <span className="text-xs font-medium px-2.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20">
          {data.partOfSpeech}
        </span>
      </div>

      {/* Definition */}
      <div className="p-3.5 rounded-xl bg-muted/50 border border-border/50">
        <p className="text-sm text-foreground leading-relaxed">{data.definition}</p>
      </div>

      {/* Examples */}
      <div className="space-y-2">
        <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Examples
        </p>
        {data.examples.map((ex, i) => (
          <div key={i} className="pl-3 border-l-2 border-primary/30 space-y-0.5">
            <p className="text-sm text-foreground italic">&ldquo;{ex.sentence}&rdquo;</p>
            <p className="text-xs text-muted-foreground">{ex.translation}</p>
          </div>
        ))}
      </div>

      {/* Synonyms */}
      <div className="flex flex-wrap gap-1.5">
        <span className="text-xs text-muted-foreground self-center">Synonyms:</span>
        {data.synonyms.map((s) => (
          <span key={s} className="text-xs px-2 py-0.5 rounded-full bg-accent text-accent-foreground">
            {s}
          </span>
        ))}
      </div>
    </motion.div>
  )
}

// ─── Main Component ───────────────────────────────────────

interface AddWordModalProps {
  open: boolean
  onClose: () => void
}

export function AddWordModal({ open, onClose }: AddWordModalProps) {
  const [step, setStep] = React.useState<Step>("input")
  const [inputWord, setInputWord] = React.useState("")
  const [wordData, setWordData] = React.useState<GeneratedWordData | null>(null)
  const [error, setError] = React.useState("")
  const inputRef = React.useRef<HTMLInputElement>(null)
  const addWord = useVocabStore((s) => s.addWord)

  // Focus input on open
  React.useEffect(() => {
    if (open) {
      setStep("input")
      setInputWord("")
      setWordData(null)
      setError("")
      setTimeout(() => inputRef.current?.focus(), 50)
    }
  }, [open])

  const handleGenerate = async () => {
    const trimmed = inputWord.trim()
    if (!trimmed) {
      setError("Please enter a word first")
      return
    }
    setError("")
    setStep("loading")
    try {
      const data = await mockGenerateWordData(trimmed)
      setWordData(data)
      setStep("preview")
    } catch {
      setError("Failed to generate. Please try again.")
      setStep("input")
    }
  }

  const handleSave = () => {
    if (!wordData) return
    addWord({ ...wordData, collection: "default" })
    setStep("saved")
    setTimeout(onClose, 1200)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && step === "input") handleGenerate()
    if (e.key === "Escape") onClose()
  }

  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      aria-label="Add new word"
    >
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Panel */}
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 12 }}
        transition={{ type: "spring", damping: 25, stiffness: 300 }}
        className="relative w-full max-w-md rounded-2xl border border-border/60 bg-card shadow-2xl overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 pt-5 pb-4 border-b border-border/40">
          <div className="flex items-center gap-2.5">
            <div className="size-7 rounded-lg gradient-primary flex items-center justify-center">
              <BookOpen className="size-3.5 text-white" />
            </div>
            <div>
              <h2 className="text-sm font-semibold">Add Word</h2>
              <p className="text-xs text-muted-foreground">AI-powered meaning inference</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <StepIndicator step={step} />
            <button
              onClick={onClose}
              className="size-7 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
              aria-label="Close"
            >
              <X className="size-4" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="p-5">
          <AnimatePresence mode="wait">
            {/* Step: Input */}
            {step === "input" && (
              <motion.div
                key="input"
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 10 }}
                className="space-y-4"
              >
                <div className="space-y-1.5">
                  <label htmlFor="word-input" className="text-sm font-medium text-foreground">
                    English word
                  </label>
                  <Input
                    id="word-input"
                    ref={inputRef}
                    value={inputWord}
                    onChange={(e) => setInputWord(e.target.value)}
                    onKeyDown={handleKeyDown}
                    placeholder="e.g. ephemeral, serendipity..."
                    className="h-11 rounded-xl border-border/60 bg-muted/30 focus:bg-background text-base"
                  />
                  {error && <p className="text-xs text-destructive">{error}</p>}
                </div>

                <div className="flex items-start gap-2.5 p-3 rounded-xl bg-primary/5 border border-primary/15">
                  <Sparkles className="size-4 text-primary shrink-0 mt-0.5" />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    AI will generate the definition, pronunciation, examples in context, and synonyms automatically.
                  </p>
                </div>

                <Button
                  onClick={handleGenerate}
                  disabled={!inputWord.trim()}
                  className="w-full h-10 rounded-xl gradient-primary border-0 text-white font-medium hover:opacity-90 transition-opacity"
                >
                  <Sparkles className="size-4" />
                  Generate with AI
                  <ChevronRight className="size-4" />
                </Button>
              </motion.div>
            )}

            {/* Step: Loading */}
            {step === "loading" && (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center justify-center py-10 gap-4"
              >
                <div className="relative size-12">
                  <div className="absolute inset-0 rounded-full gradient-primary opacity-20 animate-ping" />
                  <div className="size-12 rounded-full gradient-primary flex items-center justify-center">
                    <Loader2 className="size-5 text-white animate-spin" />
                  </div>
                </div>
                <div className="text-center space-y-1">
                  <p className="text-sm font-medium">Analyzing &ldquo;{inputWord}&rdquo;</p>
                  <p className="text-xs text-muted-foreground">Generating definition and examples...</p>
                </div>
              </motion.div>
            )}

            {/* Step: Preview */}
            {step === "preview" && wordData && (
              <motion.div
                key="preview"
                initial={{ opacity: 0, x: 10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -10 }}
                className="space-y-5"
              >
                <WordPreview data={wordData} />
                <div className="flex gap-2.5">
                  <Button
                    variant="outline"
                    onClick={() => setStep("input")}
                    className="flex-1 h-10 rounded-xl"
                  >
                    Try another
                  </Button>
                  <Button
                    onClick={handleSave}
                    className="flex-1 h-10 rounded-xl gradient-primary border-0 text-white hover:opacity-90 transition-opacity"
                  >
                    <Check className="size-4" />
                    Save word
                  </Button>
                </div>
              </motion.div>
            )}

            {/* Step: Saved */}
            {step === "saved" && (
              <motion.div
                key="saved"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="flex flex-col items-center justify-center py-10 gap-3"
              >
                <div className="size-14 rounded-full bg-green-500/15 border-2 border-green-500/30 flex items-center justify-center">
                  <Check className="size-6 text-green-500" />
                </div>
                <div className="text-center">
                  <p className="font-semibold text-foreground">Word saved!</p>
                  <p className="text-sm text-muted-foreground">&ldquo;{wordData?.word}&rdquo; added to your vocabulary</p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </motion.div>
    </div>
  )
}
