"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Sparkles, Loader2, ChevronRight, X, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useVocabStore, type VocabWord } from "@/store/vocab-store"

// ─── Types ────────────────────────────────────────────────

type Step = "input" | "loading" | "preview" | "saved"

interface GeneratedWordData {
  word: string
  phonetic: string
  definition: string
  partOfSpeech: string
  examples: VocabWord["examples"]
  synonyms: string[]
}

// ─── Mock Gemini inference ────────────────────────────────
// TODO: Replace with real Gemini API call via /api/gemini route

async function mockGenerateWordData(word: string): Promise<GeneratedWordData> {
  await new Promise((r) => setTimeout(r, 1400))

  return {
    word,
    phonetic: "/ˌmɒk.fəˈnet.ɪk/",
    definition: `A detailed definition of "${word}" generated by AI, covering its primary meaning.`,
    partOfSpeech: "adjective",
    examples: [
      {
        sentence: `The ${word} nature of the situation was apparent to everyone.`,
        translation: `Tính chất "${word}" của tình huống rõ ràng với mọi người.`,
        context: "general",
      },
      {
        sentence: `She approached the problem with a ${word} mindset.`,
        translation: `Cô ấy tiếp cận vấn đề với tư duy "${word}".`,
        context: "personal",
      },
    ],
    synonyms: ["similar", "related", "alike"],
  }
}

// ─── Word Preview ─────────────────────────────────────────

function WordPreview({ data }: { data: GeneratedWordData }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-4"
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-xl font-bold text-foreground">{data.word}</h3>
          <p className="text-sm text-muted-foreground font-mono mt-0.5">{data.phonetic}</p>
        </div>
        <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-400 shrink-0">
          {data.partOfSpeech}
        </span>
      </div>

      {/* Definition */}
      <p className="text-sm text-foreground/85 leading-relaxed">{data.definition}</p>

      {/* Examples */}
      <div className="space-y-2.5">
        {data.examples.map((ex, i) => (
          <div key={i} className="pl-3 border-l-2 border-border space-y-0.5">
            <p className="text-xs text-foreground/80 italic">&ldquo;{ex.sentence}&rdquo;</p>
            <p className="text-xs text-muted-foreground">{ex.translation}</p>
          </div>
        ))}
      </div>

      {/* Synonyms */}
      <div className="flex flex-wrap gap-1.5">
        {data.synonyms.map((s) => (
          <span key={s} className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground">
            {s}
          </span>
        ))}
      </div>
    </motion.div>
  )
}

// ─── Main Component ───────────────────────────────────────

interface AddWordModalProps {
  open: boolean
  onClose: () => void
}

export function AddWordModal({ open, onClose }: AddWordModalProps) {
  const [step, setStep] = React.useState<Step>("input")
  const [inputWord, setInputWord] = React.useState("")
  const [wordData, setWordData] = React.useState<GeneratedWordData | null>(null)
  const [error, setError] = React.useState("")
  const inputRef = React.useRef<HTMLInputElement>(null)
  const addWord = useVocabStore((s) => s.addWord)

  React.useEffect(() => {
    if (open) {
      setStep("input")
      setInputWord("")
      setWordData(null)
      setError("")
      setTimeout(() => inputRef.current?.focus(), 50)
    }
  }, [open])

  const handleGenerate = async () => {
    const trimmed = inputWord.trim()
    if (!trimmed) {
      setError("Enter a word first")
      return
    }
    setError("")
    setStep("loading")
    try {
      const data = await mockGenerateWordData(trimmed)
      setWordData(data)
      setStep("preview")
    } catch {
      setError("Something went wrong. Try again.")
      setStep("input")
    }
  }

  const handleSave = () => {
    if (!wordData) return
    addWord({ ...wordData, collection: "default" })
    setStep("saved")
    setTimeout(onClose, 1100)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && step === "input") handleGenerate()
    if (e.key === "Escape") onClose()
  }

  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      aria-label="Add new word"
    >
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="absolute inset-0 bg-black/30 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Panel */}
      <motion.div
        initial={{ opacity: 0, scale: 0.97, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.97, y: 10 }}
        transition={{ type: "spring", damping: 28, stiffness: 320 }}
        className="relative w-full max-w-md rounded-2xl border border-border/70 bg-card shadow-xl overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 pt-5 pb-4 border-b border-border/40">
          <h2 className="text-sm font-semibold">Add Word</h2>
          <button
            onClick={onClose}
            className="size-7 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            aria-label="Close"
          >
            <X className="size-4" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5">
          <AnimatePresence mode="wait">
            {/* Step: Input */}
            {step === "input" && (
              <motion.div
                key="input"
                initial={{ opacity: 0, x: -8 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 8 }}
                className="space-y-4"
              >
                <Input
                  id="word-input"
                  ref={inputRef}
                  value={inputWord}
                  onChange={(e) => setInputWord(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Enter an English word..."
                  className="h-11 rounded-xl border-border/60 bg-muted/30 focus:bg-background text-sm"
                />
                {error && <p className="text-xs text-destructive -mt-2">{error}</p>}

                <Button
                  onClick={handleGenerate}
                  disabled={!inputWord.trim()}
                  className="w-full h-10 rounded-xl bg-primary text-primary-foreground font-medium hover:bg-primary/90 transition-colors"
                >
                  <Sparkles className="size-4" />
                  Generate
                  <ChevronRight className="size-4" />
                </Button>
              </motion.div>
            )}

            {/* Step: Loading */}
            {step === "loading" && (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center justify-center py-12 gap-3"
              >
                <div className="size-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <Loader2 className="size-5 text-primary animate-spin" />
                </div>
                <p className="text-sm text-muted-foreground">Looking up &ldquo;{inputWord}&rdquo;...</p>
              </motion.div>
            )}

            {/* Step: Preview */}
            {step === "preview" && wordData && (
              <motion.div
                key="preview"
                initial={{ opacity: 0, x: 8 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -8 }}
                className="space-y-5"
              >
                <WordPreview data={wordData} />
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    onClick={() => setStep("input")}
                    className="flex-1 h-9 rounded-xl text-sm"
                  >
                    Back
                  </Button>
                  <Button
                    onClick={handleSave}
                    className="flex-1 h-9 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90 transition-colors text-sm"
                  >
                    <Check className="size-4" />
                    Save
                  </Button>
                </div>
              </motion.div>
            )}

            {/* Step: Saved */}
            {step === "saved" && (
              <motion.div
                key="saved"
                initial={{ opacity: 0, scale: 0.92 }}
                animate={{ opacity: 1, scale: 1 }}
                className="flex flex-col items-center justify-center py-12 gap-3"
              >
                <div className="size-12 rounded-full bg-green-50 dark:bg-green-500/10 flex items-center justify-center">
                  <Check className="size-5 text-green-600 dark:text-green-400" />
                </div>
                <p className="text-sm font-medium text-foreground">&ldquo;{wordData?.word}&rdquo; saved</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </motion.div>
    </div>
  )
}
